# fundamentals concepts of tensors using Tensorflow

More specific:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.functions (a way to speed up your regular Python functions)
* Using GPUs with TensorFlow(or TPYs)
* Exercises

## Introduction to Tensors

In [1]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.12.0


In [2]:
# create tensors with tf.constant()
scalar = tf.constant(10)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [3]:
# check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [4]:
# create a vector 
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check the dimension of our vector
vector.ndim

1

In [6]:
# create a matrix (hare more than one dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                               [3., 2.],
                               [5., 10.]], dtype=float)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5., 10.]], dtype=float32)>

In [8]:
# what's the number of another matrix
another_matrix.ndim

2

In [9]:
another_matrix.shape

TensorShape([3, 2])

In [10]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]],
                       [[13, 14, 15],
                       [16, 16, 18]]
                     ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 16, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* vector: a number with directions (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers (where n can by any number,
                                            a 0-dimensional tensor is scalar,
                                            a 1-dimensional tensor is vector)

 ### Creating tensors with `tf.Variable`

In [12]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try change one of teh elements in our changable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [14]:
# how about we try .assign()
changeable_tensor[1].assign(11)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10, 11], dtype=int32)>

In [15]:
# Let's try chane our unchangeable tensor
unchangeable_tensor[0].assign[9]
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### creating random tensors
Random tensors are tensors of some abitrary size which contain random numbers

In [16]:
# create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) # set seed for reproductibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

# Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.75658023, -0.06854693],
        [ 0.07595028, -1.2573844 ],
        [-0.23193759, -1.8107857 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [17]:
random_3 = tf.random.Generator.from_seed(7)
random_3 = random_3.normal(shape=(3, 2))
random_3, random_1 == random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240397 ,  0.28785658],
        [-0.87579006, -0.08856997],
        [ 0.6921164 ,  0.842157  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### shufle the order of elements in tensor

In [18]:
# shuffle a tensor (valuable for when you want to shuffle you data so the inherent order doesn't effect learning)
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 4]])

# shuffle our non_shuffled tensor
shuffled = tf.random.shuffle(not_shuffled)

not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 2,  4],
        [10,  7],
        [ 3,  4]], dtype=int32)>)

In [19]:
# shuffle our non_shuffled tensor
shuffled = tf.random.shuffle(shuffled)

not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 2,  4],
        [ 3,  4]], dtype=int32)>)

In [20]:
# shuffle our non_shuffled tensor
shuffled = tf.random.shuffle(shuffled, seed=42)

not_shuffled, shuffled

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  4]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 3,  4],
        [ 2,  4],
        [10,  7]], dtype=int32)>)

# Exercise
create random seed and suffle them

In [21]:
# create random seed using tensor

random_e1 = tf.random.Generator.from_seed(4)
random_e1 = random_e1.normal(shape=(5,3))
random_e1

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[ 1.0019135 ,  0.6735137 ,  0.06987705],
       [-1.4077919 ,  1.0278524 ,  0.2797411 ],
       [-0.01347954,  1.8451811 ,  0.9706112 ],
       [-1.0242516 , -0.6544423 , -0.29738778],
       [-1.3240397 ,  0.28785658, -0.87579006]], dtype=float32)>

In [22]:
tf.random.shuffle(random_e1)

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[-1.0242516 , -0.6544423 , -0.29738778],
       [-1.3240397 ,  0.28785658, -0.87579006],
       [-0.01347954,  1.8451811 ,  0.9706112 ],
       [-1.4077919 ,  1.0278524 ,  0.2797411 ],
       [ 1.0019135 ,  0.6735137 ,  0.06987705]], dtype=float32)>

In [23]:
random_e2 = tf.random.Generator.from_seed(7)
random_e2 = random_e2.normal(shape=(3, 4))
random_e2

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.3240397 ,  0.28785658, -0.87579006, -0.08856997],
       [ 0.6921164 ,  0.842157  , -0.06378508,  0.9280078 ],
       [-0.6039788 , -0.17669262,  0.04221032,  0.29037958]],
      dtype=float32)>

In [24]:
tf.random.shuffle(random_e2)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.6039788 , -0.17669262,  0.04221032,  0.29037958],
       [ 0.6921164 ,  0.842157  , -0.06378508,  0.9280078 ],
       [-1.3240397 ,  0.28785658, -0.87579006, -0.08856997]],
      dtype=float32)>

In [25]:
# global and random seed
tf.random.set_seed(42) # global level random seed | random but similar every other time
tf.random.shuffle(random_e2, seed=42) # operational level random seed | different each time

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-1.3240397 ,  0.28785658, -0.87579006, -0.08856997],
       [ 0.6921164 ,  0.842157  , -0.06378508,  0.9280078 ],
       [-0.6039788 , -0.17669262,  0.04221032,  0.29037958]],
      dtype=float32)>

### Other ways to make tensors

In [26]:
# create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [27]:
# create a tensor of all zeroes
tf.zeros(shape=(4,5))

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The man difference between NumPy arrays and TensorFlow is that tensors can be run on a GPY computing.


In [28]:
# you can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [29]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [30]:
A = tf.constant(A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [31]:
B = tf.constant(A, shape=(4, 3, 2))
B

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [32]:
C = tf.constant(A, shape=(8, 3))
C

<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]], dtype=int32)>

# Getting information from tensors
* Shape `tensor.shape`
* Rank `tensor.ndim`
* Axis or dimension `tensor.[0]`, `tensor[:, 1]`, ....
* Size `tf.size(tensor)`

In [33]:
# Create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
rank_4_tensor.ndim

4

In [35]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [36]:
rank_4_tensor[1]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [37]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [38]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print('Number of dimensions (rank):', rank_4_tensor.ndim)
print('Shape of tensor:', rank_4_tensor.shape)
print('Element along the 0 axis:', rank_4_tensor.shape[0])
print('Elements along the last axis:', rank_4_tensor.shape[-1])
print('Total number of elements in our tensor;', tf.size(rank_4_tensor))
print('Total number of elements in our tensor;', tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Element along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor; tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor; 120


### Indexing tensors

Tensors can be index like python list

In [39]:
# get the first element of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [40]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [41]:
# get the first element from each dimensoin from each index except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [42]:
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [43]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [44]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [45]:
# Get the last item of each of row of rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [46]:
rank_2_tensor[1, :]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>

In [47]:
rank_2_tensor[:1, :]

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[10,  7]], dtype=int32)>

In [48]:
# add in extra dimension to rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [49]:
# alternative o tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [50]:
tf.expand_dims(rank_2_tensor, axis=1) # expand the 0-axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensors operations)
**Basic Operations**

`+`, `-`, `/`

In [51]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7],[3, 5]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 15]], dtype=int32)>

In [52]:
# original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5]], dtype=int32)>

In [53]:
# Multiplicaton also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  50]], dtype=int32)>

In [54]:
# Substraction 
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -5]], dtype=int32)>

In [55]:
# we can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  50]], dtype=int32)>

In [56]:
tf.add(tensor, 4)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 11],
       [ 7,  9]], dtype=int32)>

**Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operation

In [57]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  5]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 105],
       [ 45,  46]], dtype=int32)>

In [58]:
# Matrix multiplication with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121, 105],
       [ 45,  46]], dtype=int32)>

In [59]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  25]], dtype=int32)>

In [60]:
X = tf.constant([[1, 2, 5],
                       [7, 2, 1],
                       [3, 3, 3]])
Y = tf.constant([[3, 5],
                       [6, 7],
                       [1, 8]])
X, Y

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 5],
        [7, 2, 1],
        [3, 3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [61]:
# tensorflow matrix multiplication
tf.matmul(X, Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [62]:
# python matrix multiplicaion 
X @ Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [63]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 5],
       [6, 7],
       [1, 8]], dtype=int32)>

In [64]:
X.shape, Y.shape

(TensorShape([3, 3]), TensorShape([3, 2]))

In [65]:
# Let's change the spahe of Y
tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [66]:
tensor.shape

TensorShape([2, 2])

In [67]:
tensor @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 79,  57, 116],
       [ 44,  20,  58]], dtype=int32)>

In [68]:
X = tf.constant([[1, 2], 
                [3, 4], 
                [5, 6]])
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [69]:
# can do the same with transpose
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [70]:
# matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 66],
       [36, 86]], dtype=int32)>

**The dot Product**

Matrix Multiplication is also referred to as the dot product.

You can perform matrix multiplictaion using:
* `tf.matmul()`
* `tf.tensordot()`

In [71]:
# perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [29, 46, 35],
       [45, 72, 53]], dtype=int32)>

In [72]:
# perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17,  7, 22],
       [37, 19, 50],
       [57, 31, 78]], dtype=int32)>

In [73]:
# Check the values of Y, reshape Y and transposed Y
print(f"Normal Y: ", Y)
print(f"y reshaped to (2, 3): ", tf.reshape(Y, (2, 3)))
print(f"Y transposed: ", tf.transpose(Y))

Normal Y:  tf.Tensor(
[[3 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)
y reshaped to (2, 3):  tf.Tensor(
[[3 5 6]
 [7 1 8]], shape=(2, 3), dtype=int32)
Y transposed:  tf.Tensor(
[[3 6 1]
 [5 7 8]], shape=(2, 3), dtype=int32)


In [74]:
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 20, 17],
       [29, 46, 35],
       [45, 72, 53]], dtype=int32)>

### Changing the datatype of tensor

In [75]:
# create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B, B.dtype


(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [76]:
C = tf.constant([10, 7])
C, C.dtype

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>,
 tf.int32)

In [77]:
tf.__version__

'2.12.0'

In [78]:
# Change from float32 to float16
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [79]:
 # Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([10.,  7.], dtype=float32)>,
 tf.float32)

### Aggregation tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [80]:
# Get the absolute values
D = tf.constant([-10, -11])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([-10, -11], dtype=int32)>

In [81]:
# get the absolurte values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 11], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of tensor
* Get the sum of tensor

In [82]:
# Creating a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([52, 15, 51,  1, 13, 48, 76, 58, 74,  4, 17, 47, 66, 20,  3, 71, 39,
       53,  9, 43,  2, 94, 79, 97, 41, 11, 66, 98, 41, 63, 91, 25, 29,  3,
       94, 25, 19, 38,  1, 40, 84, 86, 73, 70, 41, 35, 91, 87, 79, 33])>

In [83]:
tf.size(E, ), E.shape, E.ndim, E.dtype

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1, tf.int64)

In [84]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [85]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [86]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2396>

In [87]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=47>

***Exercise:** with what we've just learned, find the variance and standard deviation of tensor using tensorflow method

In [88]:
E = tf.constant(np.random.randint(0, 1000, size=70))
E

<tf.Tensor: shape=(70,), dtype=int64, numpy=
array([850, 251, 916, 726, 477, 505, 166, 726, 664, 761,  60, 256, 866,
       595, 402, 770, 725, 360, 737, 754, 769, 379, 873, 544, 318, 985,
       348, 313, 620, 632, 946, 315, 581, 916, 656,  51, 682,  42, 179,
       381, 415, 908, 234, 232, 175, 836, 528, 653, 583,  20, 180, 211,
        13, 551, 348, 213,  40, 888, 974, 141, 667, 722, 856, 719, 724,
       841, 203, 690, 108, 156])>

In [89]:
tf.size(E), E.ndim, E.shape

(<tf.Tensor: shape=(), dtype=int32, numpy=70>, 1, TensorShape([70]))

In [90]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [91]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=985>

In [92]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=35926>

In [93]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=513>

In [96]:
import tensorflow_probability as tfp

# variance using tensorflow-probability
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=82385>

In [97]:
# Find the standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=287.02884>

In [100]:
# find the variance of tensor
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=82385.555>

 ### Find the positional maximum and minimum

In [101]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [103]:
# find the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [104]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [105]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [107]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [108]:
# find minimum position
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [110]:
# find the minimum positional value in F
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Exercise

In [111]:
# create one big tensor
tf.random.set_seed(42)
EX1 = tf.random.uniform(shape=[1000])
EX1

<tf.Tensor: shape=(1000,), dtype=float32, numpy=
array([6.64562106e-01, 4.41006780e-01, 3.52882504e-01, 4.64482546e-01,
       3.36604118e-02, 6.84672356e-01, 7.40117431e-01, 8.72444510e-01,
       2.26326346e-01, 2.23196864e-01, 3.10388088e-01, 7.22335815e-01,
       1.33187175e-01, 5.48063874e-01, 5.74608803e-01, 8.99683475e-01,
       9.46366787e-03, 5.21230698e-01, 6.34544492e-01, 1.99328303e-01,
       7.29422450e-01, 5.45834541e-01, 1.07565522e-01, 6.76706076e-01,
       6.60276294e-01, 3.36950421e-01, 6.01417661e-01, 2.10625768e-01,
       8.52737188e-01, 4.40621734e-01, 9.48527575e-01, 2.37525940e-01,
       8.11792970e-01, 5.26339412e-01, 4.94307995e-01, 2.16128469e-01,
       8.45719695e-01, 8.71884108e-01, 3.08386207e-01, 6.86803818e-01,
       2.37640381e-01, 7.81722784e-01, 9.67138410e-01, 6.87016249e-02,
       7.98739433e-01, 6.60287142e-01, 5.87151289e-01, 1.64616942e-01,
       7.38102317e-01, 3.20540428e-01, 6.07389927e-01, 4.65234756e-01,
       9.78035450e-01, 7.223

In [112]:
# find the maximum
tf.reduce_max(EX1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99890864>

In [113]:
# find the maximum data's position
tf.argmax(EX1)

<tf.Tensor: shape=(), dtype=int64, numpy=605>

In [114]:
# Let's find the data using positional index
EX1[tf.argmax(EX1)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.99890864>

In [115]:
# find the minimum
tf.reduce_min(EX1)

<tf.Tensor: shape=(), dtype=float32, numpy=0.00019192696>

In [116]:
# find the minmum data index
tf.argmin(EX1)

<tf.Tensor: shape=(), dtype=int64, numpy=998>

In [117]:
# find the minium data using the positional index
EX1[tf.argmin(EX1)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.00019192696>

### Squeezing a tensor (removing all single dimensions)

In [119]:
# create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
           0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
           0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
           0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
           0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
           0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
           0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
           0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
           0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
           0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062]]]]],
      dtype=float32)>

In [120]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [121]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.7413678 , 0.62854624, 0.01738465, 0.3431449 , 0.51063764,
        0.3777541 , 0.07321596, 0.02137029, 0.2871771 , 0.4710616 ,
        0.6936141 , 0.07321334, 0.93251204, 0.20843053, 0.70105827,
        0.45856392, 0.8596262 , 0.92934334, 0.20291913, 0.76865506,
        0.60016024, 0.27039742, 0.88180614, 0.05365038, 0.42274463,
        0.89037776, 0.7887033 , 0.10165584, 0.19408834, 0.27896714,
        0.39512634, 0.12235212, 0.38412368, 0.9455296 , 0.77594674,
        0.94442344, 0.04296565, 0.4746096 , 0.6548251 , 0.5657116 ,
        0.13858628, 0.3004663 , 0.3311677 , 0.12907016, 0.6435652 ,
        0.45473957, 0.68881893, 0.30203617, 0.49152803, 0.26529062],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding Tensor

In [122]:
# create a list of indices
some_list = [0, 1, 2, 3]  # could be red, green, blue, purple

# One hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [123]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo I love deep learning", off_value="I also like ML")


<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like ML', b'I also like ML',
        b'I also like ML'],
       [b'I also like ML', b'yo I love deep learning', b'I also like ML',
        b'I also like ML'],
       [b'I also like ML', b'I also like ML', b'yo I love deep learning',
        b'I also like ML'],
       [b'I also like ML', b'I also like ML', b'I also like ML',
        b'yo I love deep learning']], dtype=object)>

### Exercise

In [128]:
# create another list
another_list = [1, 2, 3, 4, 5, 6, 7]

# One hot encoding 
tf.one_hot(another_list, depth=6, on_value="ML 2020", off_value="AI 2023")

<tf.Tensor: shape=(7, 6), dtype=string, numpy=
array([[b'AI 2023', b'ML 2020', b'AI 2023', b'AI 2023', b'AI 2023',
        b'AI 2023'],
       [b'AI 2023', b'AI 2023', b'ML 2020', b'AI 2023', b'AI 2023',
        b'AI 2023'],
       [b'AI 2023', b'AI 2023', b'AI 2023', b'ML 2020', b'AI 2023',
        b'AI 2023'],
       [b'AI 2023', b'AI 2023', b'AI 2023', b'AI 2023', b'ML 2020',
        b'AI 2023'],
       [b'AI 2023', b'AI 2023', b'AI 2023', b'AI 2023', b'AI 2023',
        b'ML 2020'],
       [b'AI 2023', b'AI 2023', b'AI 2023', b'AI 2023', b'AI 2023',
        b'AI 2023'],
       [b'AI 2023', b'AI 2023', b'AI 2023', b'AI 2023', b'AI 2023',
        b'AI 2023']], dtype=object)>

### square, log, sqrt

In [129]:
# create a new tensor 
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [130]:
# square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [132]:
# square root
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [134]:
# log
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

In [135]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([1., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 1.,  7., 10.])>

In [136]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 1.,  7., 10.]), numpy.ndarray)

In [137]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [139]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10,]))
tensor_J = tf.constant([3., 7., 10.])

# check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)